[package]
name = "lua"
version = "0.1.0"
authors = ["Chris Neidhart <cjneidhart@gmail.com>"]
description = "The Lua programming language, implemented in Rust."
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/cjneidhart/lua-in-rust"
